# Generated by Django 5.2.10 on 2026-01-31 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instagram_service', '0002_alter_instaclient_options_instaclient_created_at_and_more'),
        ('telegram_service', '0002_alter_botclient_language_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='telegram_service.botclient')),
                ('insta_client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='instagram_service.instaclient')),
            ],
        ),
    ]
