# Generated by Django 6.0.1 on 2026-01-31 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('instagram_service', '0002_alter_instaclient_options_instaclient_created_at_and_more'),
        ('telegram_service', '0003_alter_botclient_full_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='MainClient',
        ),
    ]
