# Generated by Django 6.0.1 on 2026-02-02 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_client_mainclient'),
        ('instagram_service', '0004_remove_instaclient_instagram_s_client__fc49b1_idx_and_more'),
        ('telegram_service', '0003_alter_botclient_full_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainclient',
            options={'verbose_name': "Bog'langan Foydalanuvchi", 'verbose_name_plural': "Bog'langan Foydalanuvchilar"},
        ),
        migrations.RemoveField(
            model_name='mainclient',
            name='bot_client',
        ),
        migrations.AlterField(
            model_name='mainclient',
            name='insta_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_clients', to='instagram_service.instaclient', unique=True),
        ),
        migrations.AddField(
            model_name='mainclient',
            name='bot_client',
            field=models.ManyToManyField(to='telegram_service.botclient'),
        ),
    ]
