# Generated by Django 6.0.1 on 2026-02-03 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_mainclient_options_and_more'),
        ('instagram_service', '0005_remove_instaclient_bio_instaclient_follower_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainclient',
            name='insta_client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_clients', to='instagram_service.instaclient'),
        ),
    ]
