# Generated by Django 5.2.10 on 2026-01-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('full_name', models.TextField()),
                ('username', models.CharField(blank=True, max_length=200, null=True)),
                ('language_code', models.CharField(default='en', max_length=2)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Telegram Foydalanuvchisi',
                'verbose_name_plural': 'Telegram Foydalanuvchilari',
            },
        ),
    ]
