# Generated by Django 5.2.10 on 2026-01-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botclient',
            name='language_code',
            field=models.CharField(default='uz', max_length=2),
        ),
    ]
