# Generated by Django 6.0.1 on 2026-01-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_service', '0002_alter_botclient_language_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botclient',
            name='full_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
