# Generated by Django 5.2.10 on 2026-01-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstaClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.BigIntegerField(unique=True)),
                ('full_name', models.TextField()),
                ('username', models.CharField(max_length=255)),
                ('bio', models.TextField()),
            ],
            options={
                'verbose_name': 'Instagram Foydadlanuvchisi',
                'verbose_name_plural': 'Instagram Foydadlanuvchilari',
            },
        ),
    ]
