# Generated by Django 5.2.10 on 2026-01-31 09:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instaclient',
            options={'ordering': ['-created_at'], 'verbose_name': 'Instagram Foydalanuvchisi', 'verbose_name_plural': 'Instagram Foydalanuvchilari'},
        ),
        migrations.AddField(
            model_name='instaclient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Yaratilgan sana'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='instaclient',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi?'),
        ),
        migrations.AddField(
            model_name='instaclient',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='Oxirgi faollik'),
        ),
        migrations.AddField(
            model_name='instaclient',
            name='profile_picture',
            field=models.URLField(blank=True, null=True, verbose_name='Profil rasmi URL'),
        ),
        migrations.AlterField(
            model_name='instaclient',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instaclient',
            name='full_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instaclient',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='instaclient',
            index=models.Index(fields=['client_id'], name='instagram_s_client__fc49b1_idx'),
        ),
        migrations.AddIndex(
            model_name='instaclient',
            index=models.Index(fields=['username'], name='instagram_s_usernam_02b569_idx'),
        ),
        migrations.AddIndex(
            model_name='instaclient',
            index=models.Index(fields=['is_active'], name='instagram_s_is_acti_dd8930_idx'),
        ),
    ]
