# Generated by Django 6.0.1 on 2026-01-31 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_service', '0002_alter_instaclient_options_instaclient_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='instaclient',
            unique_together={('client_id',)},
        ),
    ]
