# Generated by Django 6.0.1 on 2026-02-02 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_service', '0003_alter_instaclient_unique_together'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='instaclient',
            name='instagram_s_client__fc49b1_idx',
        ),
        migrations.AlterUniqueTogether(
            name='instaclient',
            unique_together=set(),
        ),
    ]
