# Generated by Django 6.0.1 on 2026-02-02 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_service', '0004_remove_instaclient_instagram_s_client__fc49b1_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instaclient',
            name='bio',
        ),
        migrations.AddField(
            model_name='instaclient',
            name='follower_count',
            field=models.IntegerField(default=0),
        ),
    ]
